sudo: false
language: python
python:
    - "2.7"
    - "3.6"
install:
    - pip install -rrequirements.txt
    - pip install coveralls
script:
    py.test --cov=sealedmock -vvvv tests
after_success:
  coveralls
